[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret="set_a_cookkie_secret_here_any_random_cokkie"

[auth.auth0]
client_id = "your client_id"
client_secret = "your client_secret"
server_metadata_url = "https://{account}.{region}.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }