# -*- coding: utf-8 -*-

from utils import load_yaml_file

# Read config data
config_data = load_yaml_file("config.yaml")

def gethomepage():
    # Disclaimer text tailored for a US-based Delaware C-Corp
    disclaimer_text = """
### Disclaimer

We're excited to present our **Minimum Viable Product (MVP)**. This AI-powered chatbot is currently in an early learning and development phase.

Please take a moment to understand the following:

* **Experimental Nature:** Responses generated by this chatbot may not always be accurate, complete, or up-to-date. The AI's capabilities are continuously evolving.
* **No Professional Advice:** The information provided by this chatbot is for general informational purposes only and does **not** constitute professional advice of any kind (e.g., medical, legal, financial, tax, or investment advice). You should not rely on the chatbot's responses as a substitute for professional consultation.
* **Content Disclaimer:** The chatbot may generate unexpected or unaligned responses. We are not responsible for any decisions made based on the information provided by the chatbot.
* **Data Usage:** By interacting with this chatbot, you acknowledge and agree that your inputs may be used to improve our services. For detailed information on how we collect, use, and protect your data, please review our [Privacy Policy](link-to-your-privacy-policy).

Your feedback is invaluable to us! If you encounter any issues or have suggestions, please don't hesitate to contact us.
"""

    markdown_string = f"""
<div style="text-align: center;">
  <img src={config_data["logo_pth"]} alt="AIFAQ logo" style="height: 110px">
  <h1>AI Agent powered by <em>AIFAQ</em> (beta)</h1>
</div>

---

## Try for free

Here the [Official GitHub Repository](https://github.com/hyperledger-labs/aifaq)

---

## Links and Resources

AIFAQ Inc. [website](https://aifaqpro.wordpress.com/)

---

## {config_data["company_name"]}

This chatbot is a {config_data["company_name"]} conversational AI tool. Please, register or login:

---

{disclaimer_text}
"""
    return markdown_string