-- ==========================================
-- AIFAQ PRO - VERSION 2 ENVIRONMENT SETUP
-- Database: VERSION2_DB
-- ==========================================

-- 1. Create Permanent Environment
CREATE DATABASE IF NOT EXISTS VERSION2_DB;
CREATE SCHEMA IF NOT EXISTS VERSION2_DB.APP_SCHEMA;
USE SCHEMA VERSION2_DB.APP_SCHEMA;

-- 2. Storage & Stages
CREATE OR REPLACE STAGE DOC_STAGE 
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') 
    DIRECTORY = (ENABLE = TRUE);

-- ==========================================
-- 3. Core Tables (From Python App Schema)
-- ==========================================

-- User-Team Mapping
CREATE TABLE IF NOT EXISTS APP_USER_TEAMS (
    USERNAME VARCHAR,
    TEAM_NAME VARCHAR,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Role Access Mapping (Team -> Category permissions)
CREATE TABLE IF NOT EXISTS ROLE_ACCESS_MAPPING (
    ROLE_NAME VARCHAR,
    ALLOWED_CATEGORY VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Admin Users
CREATE TABLE IF NOT EXISTS ADMIN_USERS (
    USERNAME VARCHAR PRIMARY KEY,
    GRANTED_BY VARCHAR,
    GRANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Teams
CREATE TABLE IF NOT EXISTS TEAMS (
    TEAM_NAME VARCHAR PRIMARY KEY,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Chat Sessions
CREATE TABLE IF NOT EXISTS CHAT_SESSIONS (
    SESSION_ID VARCHAR PRIMARY KEY,
    USERNAME VARCHAR,
    TITLE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Chat Messages
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    MESSAGE_ID VARCHAR PRIMARY KEY,
    SESSION_ID VARCHAR,
    ROLE VARCHAR,
    CONTENT VARCHAR,
    SOURCES VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Documents
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    DOC_ID VARCHAR PRIMARY KEY,
    FILENAME VARCHAR,
    CATEGORY VARCHAR,
    UPLOADED_BY VARCHAR,
    UPLOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Chunks (with Vector embeddings)
CREATE TABLE IF NOT EXISTS CHUNKS (
    CHUNK_ID VARCHAR PRIMARY KEY,
    DOC_ID VARCHAR,
    CHUNK_TEXT VARCHAR,
    CHUNK_VEC VECTOR(FLOAT, 768),
    FOREIGN KEY (DOC_ID) REFERENCES DOCUMENTS(DOC_ID)
);

-- Application Categories
CREATE TABLE IF NOT EXISTS APP_CATEGORIES (
    CATEGORY_NAME VARCHAR PRIMARY KEY,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Legacy Chat History (for compatibility)
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    SESSION_ID VARCHAR,
    USER_ROLE VARCHAR,
    QUERY_TEXT VARCHAR,
    RESPONSE_TEXT VARCHAR,
    TIMESTAMP TIMESTAMP_LTZ
);

-- ==========================================
-- 4. SECURITY POLICY (Row-Level Security)
-- ==========================================
-- Logic: Admins see ALL. Users see only what is mapped in ROLE_ACCESS_MAPPING.

CREATE OR REPLACE ROW ACCESS POLICY VERSION2_RBAC_POLICY 
AS (doc_category VARCHAR) RETURNS BOOLEAN ->
    -- Super Admins bypass checks
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'SECURITYADMIN')
    OR
    -- Regular users check the mapping table
    EXISTS (
        SELECT 1 FROM ROLE_ACCESS_MAPPING 
        WHERE ROLE_NAME = CURRENT_ROLE() 
        AND ALLOWED_CATEGORY = doc_category
    );

-- ==========================================
-- 5. SECURE VIEWS
-- ==========================================
-- Ensures the Python app can see Filenames AND respects the policy

CREATE OR REPLACE VIEW SECURE_CHUNKS_VIEW AS 
SELECT 
    c.CHUNK_ID,
    c.DOC_ID,
    c.CHUNK_TEXT,
    c.CHUNK_VEC,
    d.FILENAME,
    d.CATEGORY
FROM CHUNKS c
JOIN DOCUMENTS d ON c.DOC_ID = d.DOC_ID;

-- ==========================================
-- 6. Grant Access to Streamlit Application
-- ==========================================
-- Replace 'PUBLIC' with specific roles if you want stricter access

-- Database & Schema Access
GRANT USAGE ON DATABASE VERSION2_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA VERSION2_DB.APP_SCHEMA TO ROLE PUBLIC;

-- Read Access
GRANT SELECT ON VIEW SECURE_CHUNKS_VIEW TO ROLE PUBLIC;
GRANT SELECT ON TABLE DOCUMENTS TO ROLE PUBLIC;
GRANT SELECT ON TABLE CHUNKS TO ROLE PUBLIC;
GRANT SELECT ON TABLE APP_USER_TEAMS TO ROLE PUBLIC;
GRANT SELECT ON TABLE ROLE_ACCESS_MAPPING TO ROLE PUBLIC;
GRANT SELECT ON TABLE ADMIN_USERS TO ROLE PUBLIC;
GRANT SELECT ON TABLE TEAMS TO ROLE PUBLIC;
GRANT SELECT ON TABLE CHAT_SESSIONS TO ROLE PUBLIC;
GRANT SELECT ON TABLE CHAT_MESSAGES TO ROLE PUBLIC;
GRANT SELECT ON TABLE APP_CATEGORIES TO ROLE PUBLIC;
GRANT SELECT ON TABLE CHAT_HISTORY TO ROLE PUBLIC;

-- Write Access (for Beta simplicity)
GRANT INSERT, UPDATE, DELETE ON TABLE DOCUMENTS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE CHUNKS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE APP_USER_TEAMS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE ROLE_ACCESS_MAPPING TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE ADMIN_USERS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE TEAMS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE CHAT_SESSIONS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE CHAT_MESSAGES TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE APP_CATEGORIES TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON TABLE CHAT_HISTORY TO ROLE PUBLIC;

-- Stage Access
GRANT READ, WRITE ON STAGE DOC_STAGE TO ROLE PUBLIC;

-- ==========================================
-- 7. Apply Row Access Policy to Documents
-- ==========================================
USE SCHEMA VERSION2_DB.APP_SCHEMA;

-- Remove ANY existing policy (prevents the "already has policy" error)
ALTER TABLE DOCUMENTS DROP ALL ROW ACCESS POLICIES;

-- Attach the correct policy
ALTER TABLE DOCUMENTS 
ADD ROW ACCESS POLICY VERSION2_RBAC_POLICY ON (CATEGORY);

-- ==========================================
-- 8. Verification Queries
-- ==========================================

-- Verify policy attachment
SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
  REF_ENTITY_NAME => 'VERSION2_DB.APP_SCHEMA.DOCUMENTS', 
  REF_ENTITY_DOMAIN => 'TABLE'
));

-- Verify all tables exist
SELECT TABLE_NAME, TABLE_TYPE 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'APP_SCHEMA' 
AND TABLE_CATALOG = 'VERSION2_DB'
ORDER BY TABLE_NAME;

-- ==========================================
-- 9. Create Viewer Role for Regular Users
-- ==========================================
CREATE ROLE IF NOT EXISTS AIFAQ_VIEWER_ROLE;
GRANT USAGE ON DATABASE VERSION2_DB TO ROLE AIFAQ_VIEWER_ROLE;
GRANT USAGE ON SCHEMA VERSION2_DB.APP_SCHEMA TO ROLE AIFAQ_VIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA VERSION2_DB.APP_SCHEMA TO ROLE AIFAQ_VIEWER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA VERSION2_DB.APP_SCHEMA TO ROLE AIFAQ_VIEWER_ROLE;
GRANT READ ON STAGE VERSION2_DB.APP_SCHEMA.DOC_STAGE TO ROLE AIFAQ_VIEWER_ROLE;

-- ==========================================
-- SETUP COMPLETE
-- ==========================================
SELECT '✅ VERSION2_DB Environment Ready!' as STATUS;