-- Create database
CREATE OR REPLACE DATABASE AI_FAQ_DB;

-- Create warehouse  
CREATE OR REPLACE WAREHOUSE AI_FAQ_WH 
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE;

-- Use the new database and warehouse  
USE DATABASE AI_FAQ_DB;
USE WAREHOUSE AI_FAQ_WH;

-- Create DOCUMENTS table
CREATE OR REPLACE TABLE DOCUMENTS (
  DOC_ID VARCHAR(36) PRIMARY KEY,
  FILENAME VARCHAR(255) NOT NULL,
  FILE_TYPE VARCHAR(50),
  FILE_SIZE NUMBER,
  IS_PUBLIC BOOLEAN DEFAULT FALSE,
  UPLOADED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Create CHUNKS table  
CREATE OR REPLACE TABLE CHUNKS (
  CHUNK_ID VARCHAR(50) PRIMARY KEY,
  DOC_ID VARCHAR(36) NOT NULL,
  CHUNK_INDEX NUMBER NOT NULL,
  CHUNK_TEXT VARCHAR(10000) NOT NULL,
  FOREIGN KEY (DOC_ID) REFERENCES DOCUMENTS(DOC_ID)
);

-- Create EMBEDDINGS table
CREATE OR REPLACE TABLE EMBEDDINGS (
  CHUNK_ID VARCHAR(50) PRIMARY KEY,
  EMBEDDING ARRAY,
  FOREIGN KEY (CHUNK_ID) REFERENCES CHUNKS(CHUNK_ID)
);

-- Create CHAT_HISTORY table  
CREATE OR REPLACE TABLE CHAT_HISTORY (
  CHAT_ID VARCHAR(36) PRIMARY KEY,
  SESSION_ID VARCHAR(36) NOT NULL,
  QUERY_TEXT VARCHAR(10000) NOT NULL,
  RESPONSE_TEXT VARCHAR(10000),  
  QUERY_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()  
);

-- Grant privileges to SYSADMIN role
GRANT ALL ON DATABASE AI_FAQ_DB TO ROLE SYSADMIN;
GRANT ALL ON WAREHOUSE AI_FAQ_WH TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA AI_FAQ_DB.PUBLIC TO ROLE SYSADMIN;